### ISSUE TITLE
Why the accusations?

### ISSUE THREAD

**Issue by abbe** [GreengrayZ/VRGreen#1]
Kinda awkward to accuse me of "stealing" your code when I didn't have access to your source at all.
Taking a quick look over your source shows that you haven't learned anything from what I told you when you always asked me questions. Take a look at your AntiWorldTriggers function, you iterate through every player even though you can use a built-in function to grab players from instigatorid, then you also do object_unbox to get the type  instead of doing a simple vrc_event + 24 == 10.
It's quite ironic to think I'd take any of this code provided at all as it's just straight it terrible and riddled with bad programming practices, I'm surprised it even runs on someones computer.
You still salty I wouldn't give you my method of doing buttons or something..? Lol.

Ontop of that, nice website where you put "Dox Status: Incoming" on me and others as a poor attempt to redeem yourself, then you deleted it when you got called out, kinda odd isn't it?

**Comment by Yaekith** [comment]
quite funny actually.

**Comment by xSypherr** [comment]
> quite funny actually.
https://streamable.com/dj5zs3

quite funny actually

**Comment by xSypherr** [comment]
> Kinda awkward to accuse me of "stealing" your code when I didn't have access to your source at all.
> Taking a quick look over your source shows that you haven't learned anything from what I told you when you always asked me questions. Take a look at your AntiWorldTriggers function, you iterate through every player even though you can use a built-in function to grab players from instigatorid, then you also do object_unbox to get the type instead of doing a simple vrc_event + 24 == 10.
> It's quite ironic to think I'd take any of this code provided at all as it's just straight it terrible and riddled with bad programming practices, I'm surprised it even runs on someones computer.
> You still salty I wouldn't give you my method of doing buttons or something..? Lol.
> 
> Ontop of that, nice website where you put "Dox Status: Incoming" on me and others as a poor attempt to redeem yourself, then you deleted it when you got called out, kinda odd isn't it?

The readme is obviously a joke why you have to be mad cutiepie uwu.. unless..

**Comment by abbe** [comment]
> The readme is obviously a joke why you have to be mad cutiepie uwu.. unless..

Right, it's totally a "joke", just like the website you and greengray made that threatens a dox? Greengray even had the audacity to delete me out of credits in the latest commit, quite funny: https://i.imgur.com/I3LwOjD.png (lol'd cout)
This project is essentially a joke at this point because of the src and doing the readme even embarrassed you guys more as people who were credited on this essentially have nothing to do with it. What was the reason of this to be publically released? To show how poorly it was made and how nothing in it almost works or is useful? Come on Sypher, you try to defend your friend but you both have no clue of how anything works without having to get spoonfed and have to resort to low blows. Try again buddy.

**Comment by transIate** [comment]
svh best client there is also six rings got pwned by me and thought he was gonna log the client crash but couldn't and babyraged,

**Comment by xSypherr** [comment]
> > The readme is obviously a joke why you have to be mad cutiepie uwu.. unless..
> 
> Right, it's totally a "joke", just like the website you and greengray made that threatens a dox? Greengray even had the audacity to delete me out of credits in the latest commit, quite funny: https://i.imgur.com/I3LwOjD.png (lol'd cout)
> This project is essentially a joke at this point because of the src and doing the readme even embarrassed you guys more as people who were credited on this essentially have nothing to do with it. What was the reason of this to be publically released? To show how poorly it was made and how nothing in it almost works or is useful? Come on Sypher, you try to defend your friend but you both have no clue of how anything works without having to get spoonfed and have to resort to low blows. Try again buddy.

Why you always so angi I don't understand uwu
It's okay keep writing big text to feed ur cringe lord ego :D

**Comment by xSypherr** [comment]
> svh best client there is also six rings got pwned by me and thought he was gonna log the client crash but couldn't and babyraged,

Nice out of context flexing

**Comment by transIate** [comment]
niggas be like "abbez is so mean he wont help me >_< he has such big ego" bruh its just because hes smarter than u and u ask the most retarded questions bruh. none of what i said was out of context, considering this thread is talking about SVH, and you added in six rings, nice babyrage(1)

**Comment by xSypherr** [comment]
> niggas be like "abbez is so mean he wont help me >_< he has such big ego" bruh its just because hes smarter than u and u ask the most retarded questions bruh. none of what i said was out of context, considering this thread is talking about SVH, and you added in six rings, nice babyrage(1)

I never asked abbez anything, but I never mentioned Six rings lol

**Comment by transIate** [comment]
svh #1

**Comment by xSypherr** [comment]
> svh #1

Where can I buy svh? :)

**Comment by Yaekith** [comment]
svh #1

**Comment by Yaekith** [comment]
> > quite funny actually.
> > https://streamable.com/dj5zs3
> 
> quite funny actually

https://streamable.com/7pktf6

**Comment by Yaekith** [comment]
Oh no Skidypherr wants to buy svh so he can boost his ego even more, are you that retarded to think you can do that buddy?
Go back to sucking off Greengray, threatening to dox people and starting more drama for no reason you loser. This whole source is a meme too. https://imgur.com/a/H3TxSOe

**Comment by Yaekith** [comment]
> > svh #1
> 
> Where can I buy svh? :)

Oh no Skidypherr wants to buy svh so he can boost his ego even more, are you that retarded to think you can do that buddy?
Go back to sucking off Greengray, threatening to dox people and starting more drama for no reason you loser. This whole source is a meme too. https://imgur.com/a/H3TxSOe
https://streamable.com/7pktf6

**Comment by xSypherr** [comment]
> > > svh #1
> > 
> > 
> > Where can I buy svh? :)
> 
> Oh no Skidypherr wants to buy svh so he can boost his ego even more, are you that retarded?
> Go back to sucking off Greengray, threatening to dox people and starting more drama for no reason you loser. This whole source is a meme too. https://imgur.com/a/H3TxSOe
> https://streamable.com/7pktf6

Please don't cry on this github post, me saying I wanna buy svh is obviously a joke, but you maybe are that retarded I understand np. "so he can boost his ego even more" You are literally the one taking everything out of context, but the I gave you shit not out of context, when your gf was saying she was gonna cum :) I never threatened to dox anyone, nor start drama tbh. This is not my source so I don't care, You just take everything out of context, just like this video: https://streamable.com/7pktf6
That's literally all public information about Six, I knew this even months ago, so is that the only thing you have yaekith? You still mad? Cucklord.

**Comment by Yaekith** [comment]
Skidypherr replied, this is truly a pog moment.

**Comment by Yaekith** [comment]
What I don't get about you is the fact you like to start drama for no reason.  ¯\_(ツ)_/¯

**Comment by Yaekith** [comment]
And all of that are lies lol, none of this drama involves you Sypherr.

**Comment by xSypherr** [comment]
> What I don't get about you is the fact you like to start drama for no reason. ¯_(ツ)_/¯

Just saying: https://imgur.com/3U3CpdD
This is the biggest joke I've seen, "pressured into it" I have 2 videos that are 1h+ where you requested invite and she was like:
"oh I have an excuse it's invite only.. lets continue" LMFAO she was sucking someone else his dick while you wanted to join, you must be so mad

**Comment by Yaekith** [comment]
How could I want to join if I was fucking sleeping?

**Comment by xSypherr** [comment]
https://imgur.com/a/hEyzroP Oh really? I mean, the videos go from 8pm my time to 4am my time.
That's a long time to suck dick xd just saying

**Comment by Yaekith** [comment]
I was literally at school

**Comment by Yaekith** [comment]
Send me the full videos then, I can't make up my mind if I don't have the full story.

**Comment by xSypherr** [comment]
> I was literally at school

How can you protect a cheating whore, I don't understand.

**Comment by xSypherr** [comment]
Sure add me on discord Sypherr#0001

**Comment by Yaekith** [comment]
Because I don't know what to do, if I'm being honest, I don't know what to do either.

**Comment by Yaekith** [comment]
Accept friend request.

**Comment by abbe** [comment]
I closed this issue and you guys are still going, this isn't even related to the initial issue, stop commenting on this already and take it to direct messages lol

**Comment by LonelyLuni** [comment]
Hamburgesa
